server:
  port: 8080

spring:
  application:
    name: notification-service
  docker:
    compose:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/notification
    username: admin
    password: abcde12#

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
#      복잡한 kafka 설정은 factory bean으로 가야함
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-consumer-group
      auto-offset-reset: latest

app:
  kafka:
    topic: notification-events
